src/core/urls.py
from django.conf.urls import url

from . import views
from core.views import HomePageView, MapPageView
from core.views import EventsTodayPageView, EventsSoonPageView, EventDetailView, get_map, get_event_map, get_event_map_by_date

urlpatterns = [
	#url(r'^$', EventsTodayPageView.as_view(), name='events_today'),
	url(r'^events_todat/$', EventsTodayPageView.as_view(), name='events_today'),
	url(r'^events_soon/$', EventsSoonPageView.as_view(), name='events_soon'),
	#url(r'^map/$', MapPageView.as_view(), name='map'),
	url(r'^$', MapPageView.as_view(), name='map'),
	url(r'^contact/$', views.contact_admin, name='contact'),
	url(r'^submit/$', views.events_add, name='submit_event'),
	#url(r'^map/get_map/', get_map, name='get_map'),
	url(r'^get_map/', get_map, name='get_map'),
	url(r'^get_event_map/', get_event_map, name='get_event_map'),
	#get_event_map_by_date
	url(r'^get_event_map_by_date/', get_event_map_by_date, name='get_event_map_by_date'),
	url(r'^main/$', HomePageView.as_view(), name='home'),
	#url(r'^event_detail/(?P<pk>\d+)/$', EventDetailView.as_view(), name='event_detail'),
	url(r'^event_detail/(?P<slug>.+)/$', EventDetailView.as_view(), name='event_detail'),
	
]

src/todifua/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core', app_name='core')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="uk">
<head>
  <meta charset="UTF-8"/>
  <title>Сервіс Обліку Студентів - {% block meta_title %}{% endblock meta_title %}</title>
  <meta name="description" value="Система Обліку Студентів Навчального Закладу" />
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">
  <link rel="stylesheet"
        href="{% static "css/main.css" %}">
  <link rel="stylesheet" href="{% static "css/main.css" %}">

  {% block extra_css %}{% endblock extra_css %}

</head>
<body>

  <!-- Start Container -->
  <div class="container">

    <!-- Start Header -->
    <div class="row" id="header"> 
      <div class="col-xs-8">
        <h1>Сервіс Обліку Студентів</h1>
      </div>
      <div class="col-xs-4" id="group-selector">
        <strong>Група:</strong>
        <select>
          <option value="">Усі Студенти</option>
          <option value="">Мтм-21, Віталій Подоба</option>
          <option value="">Мтм-22, Андрій Петров</option>
        </select>
      </div>
    </div>
    <!-- End Header -->

    <!-- Start subheader -->
    <div class="row" id="sub-header"> 
      <div class="col-xs-12">
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" {% if request.path == '/' %}class="active"{% endif %}><a href="#">Студенти</a></li>
          <li role="presentation" {% if '/journal' in request.path %}class="active"{% endif %}><a href="/journal">Відвідування</a></li>
          <li role="presentation" {% if '/groups' in request.path %}class="active"{% endif %}><a href="#">Групи</a></li>
          <li role="presentation" {% if '/contact-admin' in request.path %}class="active"{% endif %}><a href="#">Контакт</a></li>
        </ul>
      </div>
    </div>
    <!-- End subheader -->

    <!-- Start Content Columns -->
    <div class="row" id="content-columns">
      <div class="col-xs-12" id="content-column">

        {% block status_message %}
        {% if request.GET.status_message %}
        <div class="alert alert-warning" role="alert">{{ request.GET.status_message }}</div>
        {% endif %}
        {% endblock %}

        <h2>{% block title %}{% endblock title %}</h2>
        {% block content %}{% endblock content %}

      </div>
    </div>
    <!-- End Content Columns -->
    
    <!-- Start Footer -->
    <div class="row" id="footer">
      <div class="col-xs-12">
        &copy; 2014 Сервіс Обліку Студентів
      </div>
    </div>
    <!-- End Footer -->

  </div>
  <!-- End Container -->
  <!-- Modal Boilerplate -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
       aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"
                  aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel"><!-- --></h4>
        </div>
        <div class="modal-body"><!-- --></div>
        <div class="modal-footer"><!-- --></div>
      </div>
    </div>
  </div>

  <!-- Javascripts Inclusion -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
  <script src="{% static "js/jquery.cookie.js" %}"></script>
  <script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script>

  <script src="{% static "js/main.js" %}"></script>
  {% block extra_js %}{% endblock extra_js %}
</body>
</html>

src/templates/base_today.html
{% load staticfiles madaotag %}

<!DOCTYPE html>
<html>

<head>



    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
	{% block extra_css %}

	{% endblock %}
<!-- 	<script src='https://api.mapbox.com/mapbox-gl-js/v0.36.0/mapbox-gl.js'></script>
	<link href='https://api.mapbox.com/mapbox-gl-js/v0.36.0/mapbox-gl.css' rel='stylesheet' /> -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" type="text/css">
    <link href="{% static 'libraries/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'libraries/entypo/style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'libraries/owl-carousel/owl.carousel.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'libraries/owl-carousel/owl.carousel.default.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/eve-black-blue.css' %}" rel="stylesheet" type="text/css" id="css-primary">
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/classic.css' %}">
    <link rel="stylesheet" href="{% static 'css/classic.date.css' %}">
    <link rel="stylesheet" href="{% static 'css/classic.time.css' %}">

    <title>today.if.ua {% block meta_title %}{% endblock meta_title %}</title>

</head>

<body class="">
<!-- FB comments -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/uk_UA/sdk.js#xfbml=1&version=v2.9&appId=1670791243225872";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!-- END FB comments -->

<div class="header-sticky">
    <div class="header-sticky-inner">
        <div class="header-logo">
            <a href="{% url 'core:home' %}">
                <span class="eve-logo"><i class="fa fa-star"></i></span> 
            </a>
        </div><!-- /.header-logo -->
<!-- Я хз шо за дівка така -->
	<div class="nav-primary navbar-toggleable-md collapse">
		<ul class="nav nav-pills">
			<li class="nav-item has-children">
				<a href="{% url 'core:home' %}" class="nav-link {% if request.path == '/main/'%} active {% endif %} ">Головна</a>

<!-- 				<ul class="sub-menu">
					<li><a href="index.html">Creative Hero</a></li>
					<li><a href="index-video.html">Video Hero</a></li>								
					<li><a href="index-map.html">Google Map Hero</a></li>
				</ul> -->
			</li>
			<li class="nav-item"><a href="{% url 'core:events_today' %}" class="nav-link {% if request.path == '/events_todat/'%} active {% endif %}">Сьогодні</a></li>
			<li class="nav-item"><a href="{% url 'core:events_soon' %}" class="nav-link {% if request.path == '/events_soon/'%} active {% endif %}">Скоро</a></li>
			<li class="nav-item"><a href="{% url 'core:map' %}" class="nav-link {% if request.path == '/'%} active {% endif %}">Події на карті</a></li>
			<!-- <li class="nav-item"><a href="blog.html" class="nav-link ">Blog</a></li> -->
			<li class="nav-item"><a href="{% url 'core:contact' %}" class="nav-link {% if request.path == '/contact/'%} active {% endif %}">Контакти</a></li>
		</ul>
	</div><!-- /.nav-primary -->

<button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target=".header .nav-primary">
	<span></span>
	<span></span>
	<span></span>
</button>	
    </div><!-- /.header-sticky-inner -->
</div><!-- /.header-sticky -->

<div class="page-wrapper">
	<div class="header-wrapper">
	<div class="header">		
		<div class="header-inner">
			<div class="header-top">
				<div class="container-fluid">
					<div class="header-logo">
						<a href="{% url 'core:home' %}">
							<span class="eve-logo"><i class="fa fa-star"></i></span> 
							<strong>
								<span>Що відбувається в місті Івано-Франківськ ?</span>
							</strong>
						</a>
					</div><!-- /.header-logo -->

					<!-- <div class="header-toggle sidenav-trigger">
					</div> -->
					<!-- /.header-toggle -->
					
					<div class="header-btn">
			<a id="propouse_event" class="btn btn-secondary" href="{% url 'core:submit_event'%}">Розмістити Подію</a><!-- /.btn -->


{#<a class="btn btn-secondary" href="{% url "core:students_add_js" %}" id="add_student_test"">Submit</a>#}
{#<a class="btn btn-secondary" href="" id="add_event"">True Submit</a>#}
<!-- /.btn -->
					</div><!-- /.header-btn -->
					<!-- Search -->
<!-- 					<div class="header-search">
						<form>
							<div class="input-group">
								<input type="text" class="form-control" 
								       autocomplete="off" 
									   data-provide="typeahead"
									   placeholder="Search for events in the city ...">

								<div class="input-group-addon">
									<i class="fa fa-search"></i>
								</div>
							</div>
						</form>
					</div> -->
					<!-- End Search -->

				</div><!-- /.container-fluid -->
			</div><!-- /.header-top -->

			<div class="header-bottom">
				<div class="container-fluid">
					<div class="nav-primary navbar-toggleable-md collapse">
	<ul class="nav nav-pills">
<!-- 		<li class="nav-item has-children">
			<a href="#" class="nav-link ">Головна</a>

			<ul class="sub-menu">
				<li><a href="index.html">Creative Hero</a></li>
				<li><a href="index-video.html">Video Hero</a></li>								
				<li><a href="index-map.html">Google Map Hero</a></li>
			</ul>
		</li> -->
		<li class="nav-item"><a href="{% url 'core:home' %}" class="nav-link {% if request.path == '/main/'%} active {% endif %}">Головна</a></li>
		<li class="nav-item"><a href="{% url 'core:events_today' %}" class="nav-link {% if request.path == '/events_todat/'%} active {% endif %}">Сьогодні</a></li>
		<li class="nav-item"><a href="{% url 'core:events_soon' %}" class="nav-link {% if request.path == '/events_soon/'%} active {% endif %}">Скоро</a></li>
		<li class="nav-item"><a href="{% url 'core:map' %}" class="nav-link {% if request.path == '/'%} active {% endif %}">Події на карті</a></li>
<!-- 		<li class="nav-item"><a href="blog.html" class="nav-link ">Blog</a></li> -->
		<li class="nav-item"><a href="{% url 'core:contact' %}" class="nav-link {% if request.path == '/contact/'%} active {% endif %}">Контакти</a></li>
	</ul>
</div><!-- /.nav-primary -->

<button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target=".header .nav-primary">
	<span></span>
	<span></span>
	<span></span>
</button>	

					<!-- <ul class="nav nav-social nav-right">
						<li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-facebook"></i></a></li>
						<li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-twitter"></i></a></li>
						<li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-google"></i></a></li>
						<li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-linkedin"></i></a></li>
					</ul>

					<ul class="nav nav-pills nav-secondary nav-right">
						<li class="nav-item"><a href="login.html" class="nav-link">Login</a></li>
						<li class="nav-item"><a href="register.html" class="nav-link">Register</a></li>
					</ul> -->					
				</div><!-- /.container-fluid -->
			</div><!-- /.header-bottom -->
		</div><!-- /.header-inner -->
	</div><!-- /.header -->
</div><!-- /.header-wrapper -->
{% block status_message %}

{% endblock status_message %}
	{% block content %}

    {% endblock %}

    <div class="footer-wrapper">
	<div class="footer">
		<div class="container-fluid">
			<div class="footer-inner">
				<div class="footer-top">
					<div class="footer-center">
						<p class="white">&copy; {% quotes %}</p>
					</div><!-- /.footer-left -->

					<!-- <div class="footer-right">
						<ul class="nav nav-social">
							<li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-facebook"></i></a></li>
							<li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-twitter"></i></a></li>
							<li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-dribbble"></i></a></li>
							<li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-linkedin"></i></a></li>
							<li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-google"></i></a></li>
						</ul>					
					</div> -->
				</div>

			</div><!-- /.footer-inner -->
		</div><!-- /.container-fluid -->
	</div><!-- /.footer -->
</div><!-- /.footer-wrapper -->




<script src="//maps.googleapis.com/maps/api/js" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>

<!-- <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCfIsnTO2FmRi3kWyLD3Es-Hb_ump6744g&libraries=places"></script> -->
<!-- <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
<script src="https://npmcdn.com/bootstrap@4.0.0-alpha.5/dist/js/bootstrap.min.js"></script> -->



<script type="text/javascript" src="{% static 'js/tether.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/bootstrap-typeahead/bootstrap3-typeahead.min.js' %}"></script>
<script type="text/javascript" src="{% static 'libraries/owl-carousel/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.gmap3.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.ytplayer.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.ezmark.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/picker.js' %}"></script>
<script type="text/javascript" src="{% static 'js/picker.date.js' %}"></script>
<script type="text/javascript" src="{% static 'js/picker.time.js' %}"></script>
<script type="text/javascript" src="{% static 'js/uk_UA.js' %}"></script>

<script type="text/javascript" src="{% static 'js/eve.js' %}"></script>


<!--   <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script> -->

<!--   <script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script> -->
<!--   <script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/js/bootstrap-datetimepicker.min.js"></script> -->
<!-- <script src="{% static 'js/main.js' %}"></script> -->

{% block extra_js %}{% endblock extra_js %}

{% block addthis %}
{% endblock %}
</body>
</html>

src/templates/students_add.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block meta_title %}Додати Студента{% endblock meta_title %}

{% block title %}Додати Студента{% endblock title %}

{% block status_message %}
  {% if errors %}
  <div class="alert alert-warning" role="alert">
    Будь-ласка, виправте наступні помилки
  </div>
  {% endif %}
{% endblock status_message %}

{% block content %}

<form action="." method="post" enctype="multipart/form-data"
      role="form" class="form-horizontal">
  {% csrf_token %}

  <div class="form-group {% if errors.first_name %}has-error{% endif %}">
    <label for="first_name" class="col-sm-2 control-label">Ім'я*</label>
    <div class="col-sm-10">
      <input type="text" value="{{ request.POST.first_name }}"
             name="first_name" id="first_name"
             class="form-control" />
      <span class="help-block">{{ errors.first_name }}</span>
    </div>
  </div>
  <div class="form-group {% if errors.last_name %}has-error{% endif %}">
    <label for="last_name" class="col-sm-2 control-label">Прізвище*</label>
    <div class="col-sm-10">
      <input type="text" value="{{ request.POST.first_name }}"
             name="last_name" id="last_name"
             placeholder="Введіть ваше прізвище"
             class="form-control" />
      <span class="help-block">{{ errors.last_name }}</span>
    </div>
  </div>
  <div class="form-group {% if errors.middle_name %}has-error{% endif %}">
    <label for="middle_name"class="col-sm-2 control-label">По-батькові</label>
    <div class="col-sm-10">
      <input type="text" value="{{ request.POST.first_name }}"
             name="middle_name" id="middle_name"
             class="form-control" />
      <span class="help-block">{{ errors.middle_name }}</span>
    </div>
  </div>
  <div class="form-group {% if errors.birthday %}has-error{% endif %}">
    <label for="birthday"class="col-sm-2 control-label">Дата Народження*</label>
    <div class="col-sm-10">
      <input type="text" value="{{ request.POST.birthday }}"
             name="birthday" id="birthday"
             placeholder="Напр. 1984-12-30"
             class="dateinput form-control" />
      <span class="help-block">{{ errors.birthday }}</span>
    </div>
  </div>
  <div class="form-group {% if errors.photo %}has-error{% endif %}">
    <label for="photo"class="col-sm-2 control-label">Фото</label>
    <div class="col-sm-10">
      <input type="file" value="" name="photoXXX" id="photo"
             class="form-control" />
      <span class="help-block">{{ errors.photo }}</span>
    </div>
  </div>
  <div class="form-group {% if errors.ticket %}has-error{% endif %}">
    <label for="ticket"class="col-sm-2 control-label">Білет*</label>
    <div class="col-sm-10">
      <input type="text" value="{{ request.POST.ticket }}"
             name="ticket" id="ticket"
             class="form-control" />
      <span class="help-block">{{ errors.ticket }}</span>
    </div>
  </div>
  <div class="form-group {% if errors.student_group %}has-error{% endif %}">
    <label for="student_group"class="col-sm-2 control-label">Група*</label>
    <div class="col-sm-10">
      <select name="student_group" id="student_group"
              class="form-control">
        <option value="">Виберіть групу</option>
        {% for group in groups %}
        <option value="{{ group.id }}" {% if group.id == request.POST.student_group|add:0 %}selected="1"{% endif %}>{{ group.title }}</option>
        {% endfor %}
      </select>
      <span class="help-block">{{ errors.student_group }}</span>
    </div>
  </div>
  <div class="form-group {% if errors.notes %}has-error{% endif %}">
    <label for="notes" class="col-sm-2 control-label">Додаткові Нотатки</label>
    <div class="col-sm-10">
      <textarea name="notes" id="notes" class="form-control">{{ request.POST.notes }}</textarea>
      <span class="help-block">{{ errors.notes }}</span>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label"></label>
    <div class="col-sm-10">
      <input type="submit" value="Додати" name="add_button"
             class="btn btn-primary" />
      <button type="submit" name="cancel_button"
              class="btn btn-link">Скасувати</button>
    </div>
  </div>
</form>


{% endblock content %}

src/templates/students_add_js.html
{% extends "base.html" %}

{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block meta_title %}Добавити Студента{% endblock meta_title %}

{% block title %}Добавити Студента{% endblock title %}

{% block status_message %}
{% if form.errors %}
<div class="alert alert-warning" role="alert">Будь-ласка, виправте наступні помилки</div>
{% endif %}
{% endblock %}

{% block content %}

{% crispy form %}

{% endblock content %}

src/templates/students_edit.html
{% extends "base.html" %}

{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block meta_title %}Редагувати Студента{% endblock meta_title %}

{% block title %}Редагувати Студента{% endblock title %}

{% block status_message %}
{% if form.errors %}
<div class="alert alert-warning" role="alert">Будь-ласка, виправте наступні помилки</div>
{% endif %}
{% endblock %}

{% block content %}

{% crispy form %}

{% endblock content %}

src/templates/students_list.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block meta_title %}Студенти{% endblock meta_title %}

{% block title %}База Студентів{% endblock title %}

{% block content %}
<a href="{% url "core:students_add" %}" class="btn btn-primary">Додати Студента</a>
<a href="{% url "core:students_add_js" %}" id="add_student_test" class="btn btn-primary">Додати Студента js</a>
<!-- Start Students Listing -->
<table class="table">
  {% with order_by=request.GET.order_by reverse=request.GET.reverse %}
  <thead>
    <tr>
      <th>#</th>
      <th>Фото</th>
      <th>
        <a href="?order_by=last_name{% if order_by == 'last_name' and reverse != '1' %}&amp;reverse=1{% endif %}">
          Прізвище
          {% if order_by == 'last_name' and reverse != '1' %}&uarr;
          {% elif order_by == 'last_name' and reverse == '1' %}&darr;
          {% endif %}
        </a>
      </th>
      <th>
        <a href="?order_by=first_name{% if order_by == 'first_name' and reverse != '1' %}&amp;reverse=1{% endif %}">
          Ім'я
          {% if order_by == 'first_name' and reverse != '1' %}&uarr;
          {% elif order_by == 'first_name' and reverse == '1' %}&darr;
          {% endif %}
      </th>
      <th>
        <a href="?order_by=ticket{% if order_by == 'ticket' and reverse != '1' %}&amp;reverse=1{% endif %}">
          № Білету
          {% if order_by == 'ticket' and reverse != '1' %}&uarr;
          {% elif order_by == 'ticket' and reverse == '1' %}&darr;
          {% endif %}
      </th>
      <th>Дії</th>
    </tr>
  </thead>
  {% endwith %}
  <tbody>
    {% for student in students %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>
        {% if student.photo %}
          <img class="img-circle" src="{{ student.photo.url }}" height="30"
               width="30" />
        {% else %}
          <img class="img-circle" src="{% static "img/default_user.png" %}"
               height="30" width="30" />
        {% endif %}
      </td>
      <td><a href="">{{ student.last_name }}</td>
      <td><a href="">{{ student.first_name }}</td>
      <td>{{ student.ticket }}</td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle"
                  data-toggle="dropdown">Дія
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{% url 'core:students_edit' student.id %}" class="student-edit-form-link">Редагувати</a></li>
            <li><a href="/journal/{{ student.id }}">Відвідування</a></li>
            <li><a href="">Видалити</a></li>
          </ul>
        </div>
      </td>
    </tr>
    {% endfor %}

  </tbody>
</table>
<!-- End Students Listing -->

{% if students.has_other_pages %}
{% with order_by=request.GET.order_by reverse=request.GET.reverse %}
<nav>
  <ul class="pagination">
    <li>
      <a href="?page=1&amp;order_by={{ order_by }}&amp;reverse={{ reverse }}">&laquo;</a>
    </li>
    {% for p in students.paginator.page_range %}
    <li {% if students.number == p %}class="active"{% endif %}>
      <a href="?page={{ p }}&amp;order_by={{ order_by }}&amp;reverse={{ reverse }}">{{ p }}</a>
    </li>
    {% endfor %}
    <li>
      <a href="?page={{ students.paginator.num_pages }}&amp;order_by={{ order_by }}&amp;reverse={{ reverse }}">
        &raquo;</a>
    </li>
  </ul>
</nav>
{% endwith %}
{% endif %}

{% endblock content %}